logging:
  level:
    root: off

spring:
  datasource:
    url: jdbc:h2:file:./bookstore;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    show-sql: false