logging:
  level:
    root: off

spring:
  datasource:
    url: jdbc:h2:file:./bookstore;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true